package ly.ulink.sdk

/**
 * E2E-harness stub. The SDK source (compiled into the test-app via srcDirs) reads
 * `ly.ulink.sdk.BuildConfig.SDK_VERSION`, which is normally generated by the
 * :ulink-sdk library module. When the source is compiled inside the test-app the
 * library's generated BuildConfig is absent, so this stub supplies it. SDK_VERSION
 * only feeds a telemetry header and is irrelevant to deep-link behavior.
 */
internal object BuildConfig {
    const val SDK_VERSION = "1.0.11-e2e"
}
